sudo: required

services:
    - docker

language: python

python:
    - "2.7"


before_install:
    - docker pull ydkdev/confd

script:
    - docker run ydkdev/confd /root/confd_all.sh -r https://github.com/psykokwak4/ydk-gen.git
