sudo: required

services:
    - docker

language: python

python:
    - "2.7"


before_install:
    - docker pull ydkdev/confd

script:
    - docker run ydkdev/confd /root/confd_all.sh -r https://github.com/$TRAVIS_REPO_SLUG.git -b $TRAVIS_BRANCH
