sudo: required

services:
    - docker

language: python

python:
    - "2.7"


before_install:
    - docker pull ydkdev/confd

script:
    - docker run ydkdev/confd /bin/bash -c './root/confd_install_ydktest.sh'
